version: 2
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: node:7
    steps:
      - checkout
      - run:
          name: Install yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: npm test -- --coverage -i
      - store_artifacts:
          path: /tmp/coverage
          destination: coverage
