version: 2
jobs:
  build:
    working_directory: ~/sham-it
    docker:
      - image: node:7
    steps:
      - checkout
      - restore_cache:
          key: sham-it-node_modules-{{ .Branch }}-{{ checksum "yarn.lock"}}
      - run:
          name: Install yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: sham-it-node_modules-{{ .Branch }}-{{ checksum "yarn.lock"}}
          paths:
            - "~/sham-it/node_modules"
      - run:
          name: Lint Files
          command: mkdir -p ~/sham-it/reports/ && npm run lint -- --format junit --output-file ~/sham-it/reports/eslint.xml
      - run:
          name: Run Tests
          command: npm test -- --coverage -i && mv test-report.xml reports/jest-junit.xml
      - store_test_results:
          path: ~/sham-it/reports
      - store_artifacts:
          path: ~/sham-it/coverage
          destination: coverage
      - run:
          name: Publish to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
        name: Semantic Release
        command: DEBUG=condition npm_config_loglevel=verbose npm run semantic-release || true
