version: 2
jobs:
  build:
    working_directory: ~/sham
    docker:
      - image: node:7
    steps:
      - checkout
      - restore_cache:
          key: sham-server-node_modules-{{ .Branch }}-{{ checksum "yarn.lock"}}
      - run:
          name: Install yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: sham-server-node_modules-{{ .Branch }}-{{ checksum "yarn.lock"}}
          paths:
            - "~/sham/node_modules"
      - run:
          name: Lint Files
          command: mkdir -p ~/sham/reports/ && npm run lint -- --format junit --output-file ~/sham/reports/eslint.xml
      - run:
          name: Run Tests
          command: npm test -- --coverage -i && mv test-report.xml reports/jest-junit.xml
      - store_artifacts:
          path: ~/sham/reports
          destination: reports
      - store_artifacts:
          path: ~/sham/coverage
          destination: coverage
      - run:
          name: Publish to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
